### ISSUE TITLE
More features from `dauden1184`

### ISSUE THREAD

**Issue by f1ren** [ftarolli/NukiBridgeAddon#2]
Can we merge this code back with `dauden1184` so we get more features?

**Comment by ftarolli** [comment]
What do u mean? Which features?

Version 0.1.1
Actually __main__.py and nuki.py are exactly the same so should have same features despite the fact that since this is an addon u don't have access to shell right now.

Anyway I built it to my specific needs but would have fun to implement it with more features and also develop some other options in configuration.
